# -*- coding: utf-8 -*-
"""Apple Stock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahHMgO6jjpOwb7Ebz8GoIhQBEQywTHDu
"""

pip install fbprophet

from fbprophet import Prophet
import numpy as np
import pandas as pd

df=pd.read_csv('/content/HistoricalQuotes.csv')

df.head()

m=Prophet()

df.describe()

df.columns

y=df.iloc[:,1]

y

train_dataset= pd.DataFrame()
train_dataset['ds'] = pd.to_datetime(df["Date"])
train_dataset['y']=y
train_dataset.head(2)

m.fit(train_dataset)

future= m.make_future_dataframe(periods=300)
future.tail(2)

forecast=m.predict(future)

m.plot(forecast)

m.plot_components(forecast)

from fbprophet.plot import add_changepoints_to_plot
fig = m.plot(forecast)
a = add_changepoints_to_plot(fig.gca(), m, forecast)

m.changepoints

pro_change= Prophet(changepoint_range=0.9)
forecast = pro_change.fit(train_dataset).predict(future)
fig= pro_change.plot(forecast);
a = add_changepoints_to_plot(fig.gca(), pro_change, forecast)

pro_change= Prophet(n_changepoints=40,changepoint_range=0.9,yearly_seasonality=True,changepoint_prior_scale=0.4,daily_seasonality=True)
forecast = pro_change.fit(train_dataset).predict(future)
fig= pro_change.plot(forecast);
a = add_changepoints_to_plot(fig.gca(), pro_change, forecast)

pro_change= Prophet(n_changepoints=10,changepoint_range=0.9,yearly_seasonality=True,changepoint_prior_scale=0.2,daily_seasonality=True,seasonality_mode='additive')
forecast = pro_change.fit(train_dataset).predict(future)
fig= pro_change.plot(forecast);
a = add_changepoints_to_plot(fig.gca(), pro_change, forecast)

